In [47]:
import pandas as pd

test = pd.read_csv('test.csv')
a = pd.read_csv('autogluon_stack3.csv')
a = a[['CI_HOUR']]
#a = a.rename(columns={'CI_HOUR': 'CI_HOUR_NEW'})
test = test[['ARI_CO','ARI_PO','ATA','U_WIND', 'V_WIND','AIR_TEMPERATURE','BN']]
test = pd.concat([test,a],axis=1)

In [43]:
import pandas as pd

# 1. train_df 데이터 로드
train_df = pd.read_csv("train.csv")
test['ATA'] = pd.to_datetime(test['ATA'])

# 2. train_df의 'ATA' 열을 datetime 형식으로 변환
train_df['ATA'] = pd.to_datetime(train_df['ATA'])

# 3. train_df를 기반으로 매핑 딕셔너리 생성
mapping_dict_train = {}
for _, row in train_df.iterrows():
    key = (row['ARI_PO'], row['U_WIND'], row['V_WIND'], row['AIR_TEMPERATURE'], row['BN'])
    mapping_dict_train[key] = (row['ATA'], row['CI_HOUR'])

# 4. 후처리 함수 정의 및 적용
def compute_post_processed_target_v11(row):
    key = (row['ARI_PO'], row['U_WIND'], row['V_WIND'], row['AIR_TEMPERATURE'], row['BN'])
    
    # 해당 샘플의 날짜보다 미래의 train_df의 데이터 중, 키가 일치하는 데이터의 날짜 참조
    if key in mapping_dict_train and mapping_dict_train[key][0] > row['ATA']:
        time_difference = (mapping_dict_train[key][0] - row['ATA']).total_seconds() / 3600
        # 시간 차이가 80일(1920시간) 이상 나는 경우 원래 값 반환
        if time_difference >= 1680: #1920, 1440, 1200, 1680
            return row['CI_HOUR']
        # 해당 Train 샘플의 CI_HOUR 값과 시간 차이를 합산하여 반환
        return abs(time_difference) + mapping_dict_train[key][1]
    
    # 일치하는 데이터가 없는 경우, 현재 값 반환
    return row['CI_HOUR']

# 함수 적용 및 결과 확인
test['Post_Processed_CI_HOUR_v11'] = test.apply(compute_post_processed_target_v11, axis=1)
print(test[['ATA', 'CI_HOUR', 'Post_Processed_CI_HOUR_v11']])

                       ATA    CI_HOUR  Post_Processed_CI_HOUR_v11
0      2020-06-18 11:58:00   4.018523                    4.018523
1      2021-05-26 22:20:00  14.224622                   14.224622
2      2019-12-16 00:09:00  25.379988                   44.690556
3      2015-11-16 05:30:00  84.764893                   84.764893
4      2018-10-24 01:11:00   0.000000                    0.000000
...                    ...        ...                         ...
220486 2017-04-04 15:53:00  58.233528                   58.233528
220487 2016-08-22 16:22:00  43.925217                   43.925217
220488 2022-07-10 14:53:00  25.632092                   13.503333
220489 2020-12-28 14:38:00   0.000000                    0.000000
220490 2015-11-07 06:34:00  58.087627                   58.087627

[220491 rows x 3 columns]

In [49]:
sub = pd.read_csv('sample_submission.csv')
sub['CI_HOUR'] = test['Post_Processed_CI_HOUR_v11']

test = pd.read_csv('test.csv')
all = pd.concat([test,sub],axis=1)
#all['CI_HOUR'][all['DIST'] == 0] = 0
all.loc[all['DIST'] == 0, 'CI_HOUR'] = 0
sub['CI_HOUR'] = all['CI_HOUR']
#sub['CI_HOUR'][submission['CI_HOUR'] < 0] = 0

sub.to_csv("SOTATEST_V3_edit_1680to1560_editN.csv",index=False)
sub

          SAMPLE_ID    CI_HOUR
0       TEST_000000   4.018523
1       TEST_000001  14.224622
2       TEST_000002  44.690556
3       TEST_000003  84.764893
4       TEST_000004   0.000000
...             ...        ...
220486  TEST_220486  58.233528
220487  TEST_220487  43.925217
220488  TEST_220488  13.503333
220489  TEST_220489   0.000000
220490  TEST_220490  58.087627

[220491 rows x 2 columns]